/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.tunisiamall.gui;

import edu.esprit.tunisiamall.JTableModels.ModelStatAdmin;
import edu.esprit.tunisiamall.dao.classes.ClientDao;
import edu.esprit.tunisiamall.dao.classes.MarqueDao;
import edu.esprit.tunisiamall.dao.classes.ResponsableEnseigneDAO;
import edu.esprit.tunisiamall.entities.Client;
import edu.esprit.tunisiamall.entities.Marque;
import edu.esprit.tunisiamall.entities.ResponsableEnseigne;
import java.awt.BorderLayout;
import java.util.List;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author antar
 */
public class AdminStat extends javax.swing.JFrame {

    /**
     * Creates new form AdminStat
     */
    public AdminStat() {
        initComponents();
        populateJTable();
        RemplirAlert();
        prepareSTAT();
    }
    
    
    
    
    public void populateJTable(){
       
        ResponsableEnseigneDAO rdao= new ResponsableEnseigneDAO();
        ResponsableEnseigne r= new ResponsableEnseigne();
        MarqueDao mdao= new MarqueDao();
        Marque m = new Marque();
        
        
        
        List<ResponsableEnseigne> list =rdao.Display();
        
        String[] columnName = {"Nom","Prénom","Marque","Email"};
        Object[][] rows = new Object[list.size()][4];
        for(int i = 0; i < list.size(); i++){
            //System.out.println("**************"+list.get(i).getId_local());
            
            m.setNom(mdao.getNameMarqueByResponsable(list.get(i).getId()));
            //System.out.println("**************"+m.getNom());
            
            rows[i][0] = list.get(i).getNom();
            rows[i][1] = list.get(i).getPrenom();
            rows[i][2] = m.getNom();
            rows[i][3] = list.get(i).getMail();
              
        }
        
        ModelStatAdmin model = new ModelStatAdmin(rows, columnName);
        TableResponsable.setModel(model);
        TableResponsable.setRowHeight(80);
        TableResponsable.getColumnModel().getColumn(2).setPreferredWidth(100);
    }
    
    
     public void RemplirAlert(){
    String alerte=""; //POSSIBLITE DE OPTIMISER !!!
    ClientDao cdao = new ClientDao();
    Client c = new Client();
    List<Client> list=cdao.DisplayBlockedClients();
       for(int i = 0; i < list.size(); i++){
       alerte=alerte+i+": User Name: "+list.get(i).getLogin()+", Nom: "+list.get(i).getNom()+", Prénom: "+list.get(i).getPrenom()+"\n";
       TextAreaBlockedClient.setText(alerte);
       
       }
       
     }
     
     public void prepareSTAT(){
         
         ResponsableEnseigneDAO rdao = new ResponsableEnseigneDAO();
         ClientDao cdao = new ClientDao();
         
         List<Client> listHomme=cdao.DisplayMaleClients();
//         for(int i=0;i<listHomme.size();i++){
//          nbrHOMME+=1;
//          }
         
          List<Client> listFemme=cdao.DisplayFemaleClients();
//          for(int i=0;i<listFemme.size();i++){
//          nbrFemme+=1;
//          }
          
          System.out.println("le nbr Homme est :"+listHomme.size());
          System.out.println("le nbr femme est :"+listFemme.size());
          
          
       //nbrHOMME=(nbrHOMME*100)/(nbrHOMME+nbrFemme);  
       //nbrFemme=(nbrFemme*100)/(nbrHOMME+nbrFemme); 
      DefaultPieDataset dataset = new DefaultPieDataset( );
      dataset.setValue("Homme", new Double(listHomme.size()) );
      dataset.setValue("Femme", new Double( listFemme.size() ) );
      

      JFreeChart chart = ChartFactory.createPieChart(
         "Sexe des clients", // chart title
         dataset, // data
         true, // include legend
         true,
         false);
         
     ChartPanel panel = new ChartPanel(chart);
        CP.setLayout(new java.awt.BorderLayout());
        CP.add(panel,BorderLayout.CENTER);
        CP.validate();
         
         
         
       
     }
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaBlockedClient = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableResponsable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CP = new javax.swing.JPanel();
        BtnRetour = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextAreaBlockedClient.setColumns(20);
        TextAreaBlockedClient.setRows(5);
        jScrollPane1.setViewportView(TextAreaBlockedClient);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 215, 164));

        jLabel1.setText("Client Bloqués:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, 112, -1));

        TableResponsable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TableResponsable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 556, 919, 130));

        jLabel2.setFont(new java.awt.Font("Tunga", 0, 18)); // NOI18N
        jLabel2.setText("Liste des Responsables d'enseignes : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 514, 273, -1));

        jLabel3.setFont(new java.awt.Font("Tunga", 0, 18)); // NOI18N
        jLabel3.setText("Statistiques des Utilisateurs");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 220, 21));

        javax.swing.GroupLayout CPLayout = new javax.swing.GroupLayout(CP);
        CP.setLayout(CPLayout);
        CPLayout.setHorizontalGroup(
            CPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );
        CPLayout.setVerticalGroup(
            CPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        getContentPane().add(CP, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 64, -1, -1));

        BtnRetour.setBackground(new java.awt.Color(0, 204, 153));
        BtnRetour.setForeground(new java.awt.Color(255, 255, 255));
        BtnRetour.setText("Retour");
        BtnRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetourActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRetour, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 712, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/tunisiamall/images/adminstat.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetourActionPerformed
        // TODO add your handling code here:
        HomeAdmin HM = new HomeAdmin();
        HM.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnRetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminStat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminStat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminStat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminStat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminStat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRetour;
    private javax.swing.JPanel CP;
    private javax.swing.JTable TableResponsable;
    private javax.swing.JTextArea TextAreaBlockedClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
