/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.tunisiamall.gui;


import edu.esprit.tunisiamall.dao.classes.ClientDao;
import edu.esprit.tunisiamall.entities.Client;
import edu.esprit.tunisiamall.entities.TheModal;
import edu.esprit.tunisiamall.notificationAdmin.Notifieur;
import edu.esprit.tunisiamall.notificationAdmin.TypeNotification;
import java.awt.Color;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author dali
 */
public class FormulaireClient extends javax.swing.JFrame {

    /**
     * Creates new form FormulaireClient
     */
    
    private boolean loginValide=false,passwordValide=false,nomValide=false,prenomValide=false,mailValide=false,adresseValide=false,telephoneValide=false,cinValide=false;
    
    public FormulaireClient() {
        initComponents();
        getContentPane().setBackground(Color.decode("#FFFFFF"));
        this.setLocationRelativeTo(null);
        
        exit.setToolTipText("Acceuil");
        
//        getRootPane().setDefaultButton(add);
//        add.requestFocus();
        
        ClientDao rdao = new ClientDao();
        Client resp = new Client ();
        
        
//        List<Client> list=rdao.Display();
//        DefaultTableModel model =(DefaultTableModel) tableClient.getModel();
//        for(Client cc:list){
//            int x = cc.getEtat();
//            String bl ;
//            if (x==2) {  bl = "Non Bloqueé" ; } else {bl="bloquée" ;}
//           model.addRow(new Object[]{cc.getId(),cc.getPrenom(),cc.getNom(),cc.getCin(),
//               cc.getLogin(),cc.getPassword(),cc.getMail(),cc.getAdresse(),cc.getTelephone(),bl}); 
//        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClient = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableClient1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setForeground(new java.awt.Color(0, 204, 153));
        exit.setText("Retour");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 80, 30));

        tableClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "login", "nom", "prenom", "mail", "adresse", "telephone", "etat"
            }
        ));
        tableClient.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tableClientMouseMoved(evt);
            }
        });
        tableClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClientMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tableClientMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(tableClient);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 490, 150));

        tableClient1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableClient1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tableClient1MouseMoved(evt);
            }
        });
        tableClient1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClient1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableClient1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 490, 150));

        jLabel2.setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        jLabel2.setText("Liste des clients");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 260, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/tunisiamall/images/adminclient.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        HomeAdmin home = null;
        home = new HomeAdmin();
         this.setVisible(false);
        home.setVisible(true);
       
    }//GEN-LAST:event_exitActionPerformed

    private void tableClientMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClientMouseMoved
        // TODO add your handling code here:
       
        ClientDao cdao = new ClientDao();
        Client clt = new Client ();
         List<Client> list=cdao.Display();
         String[] columnName = {"login","nom","prenom","mail","adresse","telephone","etat"};
        Object[][] rows = new Object[list.size()][7];
        for(int i = 0; i < list.size(); i++){
            rows[i][0] = list.get(i).getLogin();
            rows[i][1] = list.get(i).getNom();
            rows[i][2] = list.get(i).getPrenom();
             rows[i][3] = list.get(i).getEmail();
             rows[i][4] = list.get(i).getAdresse();
             rows[i][5] = list.get(i).getTelephone();
            // rows[i][6] = list.get(i).getRole();
             
            rows[i][6] = list.get(i).getEtat();
            
        }
             TheModal model = new TheModal(rows, columnName);
        tableClient.setModel(model);
        
        tableClient.setRowHeight(60);        // TODO add your handling code here:
        
   tableClient1MouseMoved(evt);
    }//GEN-LAST:event_tableClientMouseMoved

    private void tableClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClientMouseClicked
 TheModal model=(TheModal) tableClient.getModel();
         int index =tableClient.getSelectedRow();
         int intr= tableClient.getSelectedColumn();
         String login=model.getValueAt(index, 0).toString();
        
         Client c= new Client();
         c.setLogin(login);
         ClientDao CDAO=new  ClientDao();
         CDAO.Block(c);
         tableClient1MouseMoved(evt);
         Notifieur notif= new Notifieur("*INFORMATION*", 
				"Vous avez bloqué un client", 
				TypeNotification.INFO);
          notif.start();
    }//GEN-LAST:event_tableClientMouseClicked

    private void tableClientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClientMouseExited

    }//GEN-LAST:event_tableClientMouseExited

    private void tableClient1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClient1MouseMoved
        // TODO add your handling code here:
        
        ClientDao cdao = new ClientDao();
        Client clt = new Client ();
         List<Client> list=cdao.Display1();
         String[] columnName = {"login","nom","prenom","mail","adresse","telephone","etat"};
        Object[][] rows = new Object[list.size()][7];
        for(int i = 0; i < list.size(); i++){
            rows[i][0] = list.get(i).getLogin();
            rows[i][1] = list.get(i).getNom();
            rows[i][2] = list.get(i).getPrenom();
             rows[i][3] = list.get(i).getEmail();
             rows[i][4] = list.get(i).getAdresse();
             rows[i][5] = list.get(i).getTelephone();
            // rows[i][6] = list.get(i).getRole();
             
            rows[i][6] = list.get(i).getEtat();
            
        }
             TheModal model = new TheModal(rows, columnName);
        tableClient1.setModel(model);
        
        tableClient1.setRowHeight(60);        // TODO add your handling code here:
       
    }//GEN-LAST:event_tableClient1MouseMoved

    private void tableClient1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClient1MouseClicked
        // TODO add your handling code here:
        TheModal model=(TheModal) tableClient1.getModel();
         int index =tableClient1.getSelectedRow();
      //  int ind=tableClient.getSelectedRow();
    //  int intr= tableClient1.getSelectedColumn();
//      String a= model.getValueAt(index, 5).toString();
//        System.out.println(a);
        String login=model.getValueAt(index, 0).toString();
       Client c= new Client();
       c.setLogin(login);
        ClientDao CDAO=new  ClientDao();
        CDAO.DEBlock(c);
        
       // int index= tableClient.getColumnCount();
       // String index1 =tableClient.getColumnName(6);
         System.out.println(login);   
          tableClientMouseMoved(evt);
          Notifieur notif= new Notifieur("*INFORMATION*", 
				"Vous avez débloqué un client", 
				TypeNotification.INFO);
          notif.start();
    }//GEN-LAST:event_tableClient1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormulaireClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormulaireClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormulaireClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormulaireClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormulaireClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableClient;
    private javax.swing.JTable tableClient1;
    // End of variables declaration//GEN-END:variables
}
