/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.tunisiamall.gui;

import edu.esprit.tunisiamall.JTableModels.ModelLocaux;
import edu.esprit.tunisiamall.dao.classes.LocalDao;
import edu.esprit.tunisiamall.entities.Local;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author antar
 */
public class GestionLocaux extends javax.swing.JFrame {

    /**
     * Creates new form GestionLocaux
     */
    public GestionLocaux() {
        initComponents();
        populateJTable();
        
    }
    
    public void populateJTable(){
        
        LocalDao ldao = new LocalDao();
        Local l = new Local();
        
 
        List<Local> list=ldao.afficherLocal();
        String[] columnName = {"Adresse","Etat"};
        Object[][] rows = new Object[list.size()][2];
        for(int i = 0; i < list.size(); i++){
            
            rows[i][0] = list.get(i).getAdresse();
            
            if(list.get(i).getEtat()==1){
            rows[i][1] = "Réservé";
            }
            else{
            rows[i][1] = "Disponible";
            }
           
            
        }
        
        ModelLocaux model = new ModelLocaux(rows, columnName);
        TableLocaux.setModel(model);
        TableLocaux.setRowHeight(80);
        //TableLocal.getColumnModel().getColumn(2).setPreferredWidth(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelAdresse = new javax.swing.JLabel();
        LabelEtat = new javax.swing.JLabel();
        TextFieldAdresse = new javax.swing.JTextField();
        TextFieldEtat = new javax.swing.JTextField();
        BtnAjout = new javax.swing.JButton();
        BtnSuppression = new javax.swing.JButton();
        BtnReservation = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableLocaux = new javax.swing.JTable();
        BtnRetour = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(963, 568));
        setMinimumSize(new java.awt.Dimension(963, 568));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelAdresse.setText("Adresse: ");
        getContentPane().add(LabelAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        LabelEtat.setText("Etat:");
        getContentPane().add(LabelEtat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 34, -1));

        TextFieldAdresse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldAdresseFocusGained(evt);
            }
        });
        getContentPane().add(TextFieldAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 140, -1));
        getContentPane().add(TextFieldEtat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 140, -1));

        BtnAjout.setBackground(new java.awt.Color(0, 204, 153));
        BtnAjout.setForeground(new java.awt.Color(255, 255, 255));
        BtnAjout.setText("Ajouter");
        BtnAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAjoutActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAjout, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 195, -1, -1));

        BtnSuppression.setBackground(new java.awt.Color(0, 204, 153));
        BtnSuppression.setForeground(new java.awt.Color(255, 255, 255));
        BtnSuppression.setText("Supprimer");
        getContentPane().add(BtnSuppression, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 195, -1, -1));

        BtnReservation.setBackground(new java.awt.Color(0, 204, 153));
        BtnReservation.setForeground(new java.awt.Color(255, 255, 255));
        BtnReservation.setText("Réserver");
        getContentPane().add(BtnReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 195, -1, -1));

        TableLocaux.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableLocaux.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableLocauxMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableLocaux);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 252, -1, 191));

        BtnRetour.setBackground(new java.awt.Color(0, 204, 153));
        BtnRetour.setForeground(new java.awt.Color(255, 255, 255));
        BtnRetour.setText("Retour");
        BtnRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetourActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRetour, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 420, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 204, 153));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/tunisiamall/images/glocaux.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableLocauxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableLocauxMouseClicked
        // TODO add your handling code here:
        int i = TableLocaux.getSelectedRow();
        TableModel model = TableLocaux.getModel();
        TextFieldAdresse.setText(model.getValueAt(i,0).toString());
        TextFieldAdresse.setEditable(false);
        TextFieldEtat.setText(model.getValueAt(i,1).toString());
        TextFieldEtat.setEditable(false);
        if((model.getValueAt(i,1).toString())=="Réservé"){
            BtnReservation.setText("Libérer");
        }
        else{
            BtnReservation.setText("Réserver"); 
        }
    }//GEN-LAST:event_TableLocauxMouseClicked

    private void BtnAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAjoutActionPerformed
        // TODO add your handling code here:
        Component frame = null;
        LocalDao ldao = new LocalDao();
        Local l = new Local();
        l.setAdresse(TextFieldAdresse.getText());
        l.setEtat(0);
        l.setEmplacement("Emplacement"+TextFieldAdresse.getText());
        if(ldao.ajouterLocal(l)){
        JOptionPane.showMessageDialog(frame, "Local Ajouté avec succés !");
        }
        else{
        JOptionPane.showMessageDialog(frame, "Local n'a pas été Ajouté avec succés !");
        }
        
        
        populateJTable();
        
    }//GEN-LAST:event_BtnAjoutActionPerformed

    private void TextFieldAdresseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldAdresseFocusGained
        // TODO add your handling code here:
        TextFieldEtat.setText("Disponible");
        TextFieldEtat.setEditable(false);
    }//GEN-LAST:event_TextFieldAdresseFocusGained

    private void BtnRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetourActionPerformed
        // TODO add your handling code here:
        HomeAdmin HM = new HomeAdmin();
        HM.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnRetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionLocaux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionLocaux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionLocaux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionLocaux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionLocaux().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAjout;
    private javax.swing.JButton BtnReservation;
    private javax.swing.JButton BtnRetour;
    private javax.swing.JButton BtnSuppression;
    private javax.swing.JLabel LabelAdresse;
    private javax.swing.JLabel LabelEtat;
    private javax.swing.JTable TableLocaux;
    private javax.swing.JTextField TextFieldAdresse;
    private javax.swing.JTextField TextFieldEtat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
