/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.tunisiamall.gui;

import AppPackage.AnimationClass;
import edu.esprit.tunisiamall.dao.classes.ClientDao;
import edu.esprit.tunisiamall.entities.Client;
import edu.esprit.tunisiamall.utils.Utilis;
import java.awt.Toolkit;
import java.util.HashSet;
import javafx.animation.Animation;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;


/**
 *
 * @author Fatma Jaafar
 */

public class iNSCRIPTION extends javax.swing.JFrame {
int xMouse;
    int yMouse;
//     WebCamFormMaryem webC;
    
    /**
     * Creates new form iNSCRIPTION
     */
    public iNSCRIPTION() {
         // webC= new WebCamFormMaryem();
      SetIcon();
        initComponents();
       
notiferrphoto.setVisible(false);
errmsg.setVisible(false);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CLOSE = new javax.swing.JLabel();
        minim = new javax.swing.JLabel();
        drag = new javax.swing.JLabel();
        nominput = new javax.swing.JTextField();
        prenominput = new javax.swing.JTextField();
        logininput = new javax.swing.JTextField();
        adresseinput = new javax.swing.JTextField();
        motdepasseinput = new javax.swing.JPasswordField();
        emailinput = new javax.swing.JTextField();
        sinscrire = new javax.swing.JLabel();
        sexeinput = new javax.swing.JComboBox();
        errmsg = new javax.swing.JLabel();
        notiferrphoto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bglabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inscription");
        setMinimumSize(new java.awt.Dimension(1260, 720));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CLOSE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/tunisiamall/images/close.png"))); // NOI18N
        CLOSE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLOSEMouseClicked(evt);
            }
        });
        getContentPane().add(CLOSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 50, 50));

        minim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/tunisiamall/images/minim.png"))); // NOI18N
        minim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimMouseClicked(evt);
            }
        });
        getContentPane().add(minim, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, -10, 60, 70));

        drag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragMouseDragged(evt);
            }
        });
        drag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragMousePressed(evt);
            }
        });
        getContentPane().add(drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 1170, 70));

        nominput.setFont(new java.awt.Font("MV Boli", 0, 11)); // NOI18N
        nominput.setForeground(new java.awt.Color(255, 255, 255));
        nominput.setText("Entrez votre nom...");
        nominput.setBorder(null);
        nominput.setOpaque(false);
        nominput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nominputFocusLost(evt);
            }
        });
        nominput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nominputMouseClicked(evt);
            }
        });
        getContentPane().add(nominput, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 450, 30));

        prenominput.setFont(new java.awt.Font("MV Boli", 0, 11)); // NOI18N
        prenominput.setForeground(new java.awt.Color(255, 255, 255));
        prenominput.setText("Entrez votre prénom...");
        prenominput.setBorder(null);
        prenominput.setOpaque(false);
        prenominput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                prenominputFocusLost(evt);
            }
        });
        prenominput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prenominputMouseClicked(evt);
            }
        });
        getContentPane().add(prenominput, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 450, 30));

        logininput.setFont(new java.awt.Font("MV Boli", 0, 11)); // NOI18N
        logininput.setForeground(new java.awt.Color(255, 255, 255));
        logininput.setText("Entrez votre login");
        logininput.setBorder(null);
        logininput.setOpaque(false);
        logininput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                logininputFocusLost(evt);
            }
        });
        logininput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logininputMouseClicked(evt);
            }
        });
        getContentPane().add(logininput, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 440, 30));

        adresseinput.setFont(new java.awt.Font("MV Boli", 0, 11)); // NOI18N
        adresseinput.setForeground(new java.awt.Color(255, 255, 255));
        adresseinput.setText("Entrez votre adresse...");
        adresseinput.setBorder(null);
        adresseinput.setOpaque(false);
        adresseinput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                adresseinputFocusLost(evt);
            }
        });
        adresseinput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adresseinputMouseClicked(evt);
            }
        });
        getContentPane().add(adresseinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 430, 30));

        motdepasseinput.setForeground(new java.awt.Color(255, 255, 255));
        motdepasseinput.setText("jPasswordField1");
        motdepasseinput.setBorder(null);
        motdepasseinput.setOpaque(false);
        motdepasseinput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                motdepasseinputMouseClicked(evt);
            }
        });
        getContentPane().add(motdepasseinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 440, 30));

        emailinput.setFont(new java.awt.Font("MV Boli", 0, 11)); // NOI18N
        emailinput.setForeground(new java.awt.Color(255, 255, 255));
        emailinput.setText("Entrez votre email ...");
        emailinput.setBorder(null);
        emailinput.setOpaque(false);
        emailinput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailinputFocusLost(evt);
            }
        });
        emailinput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailinputMouseClicked(evt);
            }
        });
        emailinput.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                emailinputInputMethodTextChanged(evt);
            }
        });
        emailinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailinputActionPerformed(evt);
            }
        });
        getContentPane().add(emailinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 430, 30));

        sinscrire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sinscrireMouseClicked(evt);
            }
        });
        getContentPane().add(sinscrire, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 360, 100, 30));

        sexeinput.setBackground(new java.awt.Color(204, 204, 255));
        sexeinput.setForeground(new java.awt.Color(255, 255, 255));
        sexeinput.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Femme", "Homme" }));
        sexeinput.setBorder(null);
        sexeinput.setOpaque(false);
        sexeinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexeinputActionPerformed(evt);
            }
        });
        getContentPane().add(sexeinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 630, -1, 20));

        errmsg.setForeground(new java.awt.Color(204, 204, 204));
        errmsg.setText("Invalide");
        getContentPane().add(errmsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 690, 220, 20));

        notiferrphoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/tunisiamall/images/notifications.png"))); // NOI18N
        getContentPane().add(notiferrphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 680, 340, 40));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ajoutez votre photo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 630, 140, -1));

        bglabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/tunisiamall/images/inscription.png"))); // NOI18N
        getContentPane().add(bglabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CLOSEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLOSEMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CLOSEMouseClicked

    private void minimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimMouseClicked
        this.setState(iNSCRIPTION.ICONIFIED);
    }//GEN-LAST:event_minimMouseClicked

    private void dragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_dragMouseDragged

    private void sexeinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexeinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexeinputActionPerformed

    private void dragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMousePressed
xMouse=evt.getX();
        yMouse=evt.getY();         // TODO add your handling code here:
    }//GEN-LAST:event_dragMousePressed

    private void nominputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nominputMouseClicked
nominput.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_nominputMouseClicked

    private void prenominputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prenominputMouseClicked
prenominput.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_prenominputMouseClicked

    private void logininputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logininputMouseClicked
logininput.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_logininputMouseClicked

    private void motdepasseinputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_motdepasseinputMouseClicked
motdepasseinput.setText("");
                // TODO add your handling code here:
    }//GEN-LAST:event_motdepasseinputMouseClicked

    private void adresseinputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adresseinputMouseClicked
adresseinput.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_adresseinputMouseClicked

    private void emailinputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailinputMouseClicked
emailinput.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_emailinputMouseClicked

    private void emailinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailinputActionPerformed
        
    }//GEN-LAST:event_emailinputActionPerformed

    private void emailinputInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_emailinputInputMethodTextChanged
    

// TODO add your handling code here:
    }//GEN-LAST:event_emailinputInputMethodTextChanged

    private void emailinputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailinputFocusLost
      notiferrphoto.setVisible(true);
errmsg.setVisible(true);
        AnimationClass AC= new AnimationClass();
         AC.jLabelYUp(680, 660, 7, 4, notiferrphoto);
      AC.jLabelYUp(690, 670, 7, 4, errmsg);
        if (!Utilis.isValid(emailinput.getText())){
             errmsg.setText("email ".concat(errmsg.getText()));
             
             }
        else {errmsg.setVisible(false);   
        notiferrphoto.setVisible(false);
        
        } 
       AC.jLabelYDown(660, 680, 7, 4, notiferrphoto);
      AC.jLabelYDown(670, 690, 7, 4, errmsg); 
// TODO add your handling code here:
    }//GEN-LAST:event_emailinputFocusLost

    private void logininputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_logininputFocusLost
       AnimationClass AC= new AnimationClass();
        ClientDao cdao= new ClientDao();
        
    Client c= cdao.researchclient(logininput.getText());
    if (null!=c){     notiferrphoto.setVisible(true);
                       errmsg.setVisible(true);
 
        
      AC.jLabelYUp(680, 660, 7, 4, notiferrphoto);
      AC.jLabelYUp(690, 670, 7, 4, errmsg);
            errmsg.setText("login EXISTANT".concat(errmsg.getText()));
    }
         
        else {errmsg.setVisible(false);   
        notiferrphoto.setVisible(false);
        
        }
       AC.jLabelYDown(660, 680, 7, 4, notiferrphoto);
      AC.jLabelYDown(670, 690, 7, 4, errmsg); 
    }//GEN-LAST:event_logininputFocusLost

    private void adresseinputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adresseinputFocusLost
//             notiferrphoto.setVisible(true);
//errmsg.setVisible(true);
//        AnimationClass AC= new AnimationClass();
//         AC.jLabelYUp(680, 660, 7, 4, notiferrphoto);
//      AC.jLabelYUp(690, 670, 7, 4, errmsg);
//        if (!Utilis.isAlphanumeric(adresseinput.getText())){
//          errmsg.setText("adresse ".concat(errmsg.getText()));
//             
//             }
//        else {errmsg.setVisible(false);   
//        notiferrphoto.setVisible(false);
//        
//        } 
//       AC.jLabelYDown(660, 680, 7, 4, notiferrphoto);
//      AC.jLabelYDown(670, 690, 7, 4, errmsg); // TODO add your handling code here:
    }//GEN-LAST:event_adresseinputFocusLost

    private void nominputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nominputFocusLost
//                 notiferrphoto.setVisible(true);
//errmsg.setVisible(true);
//        AnimationClass AC= new AnimationClass();
//         AC.jLabelYUp(680, 660, 7, 4, notiferrphoto);
//      AC.jLabelYUp(690, 670, 7, 4, errmsg);
//        if (!Utilis.isAlphabetic(nominput.getText())){
//            errmsg.setText("nom ".concat(errmsg.getText()));
//             
//             }
//        else {errmsg.setVisible(false);   
//        notiferrphoto.setVisible(false);
//        
//        } 
//       AC.jLabelYDown(660, 680, 7, 4, notiferrphoto);
//      AC.jLabelYDown(670, 690, 7, 4, errmsg);   // TODO add your handling code here:
    }//GEN-LAST:event_nominputFocusLost

    private void prenominputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prenominputFocusLost
//                      notiferrphoto.setVisible(true);
//        errmsg.setVisible(true);
//        AnimationClass AC= new AnimationClass();
//         AC.jLabelYUp(680, 660, 7, 4, notiferrphoto);
//      AC.jLabelYUp(690, 670, 7, 4, errmsg);
//        if (!Utilis.isAlphabetic(prenominput.getText())){
//      errmsg.setText("prenom ".concat(errmsg.getText()));
//             
//             }
//        else {errmsg.setVisible(false);   
//        notiferrphoto.setVisible(false);
//        
//        } 
//       AC.jLabelYDown(660, 680, 7, 4, notiferrphoto);
//      AC.jLabelYDown(670, 690, 7, 4, errmsg);  // TODO add your handling code here:
    }//GEN-LAST:event_prenominputFocusLost

    private void sinscrireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinscrireMouseClicked
        notiferrphoto.setVisible(false);
        errmsg.setVisible(false);
        ClientDao cdao= new ClientDao();
    //Client etd= cdao.researchclient(logininput.getText());
        if (nominput.getText().equals("") 
          ||   prenominput.getText().equals("")
          ||   logininput.getText().equals("") 
          ||   motdepasseinput.getText().equals("")
          ||   adresseinput.getText().equals("") 
          ||   emailinput.getText().equals("") )       
        {
        JOptionPane.showMessageDialog(rootPane, "champs vides !","Erreur", JOptionPane.ERROR_MESSAGE);
        
        }
        else if ((cdao.researchclient(logininput.getText())!=null) || !Utilis.isValid(emailinput.getText()))    
        {JOptionPane.showMessageDialog(rootPane, "champs invalides!","Erreur", JOptionPane.ERROR_MESSAGE);}
        else { 
            Client etd= new Client();
        etd.setNom( nominput.getText().toString());
        etd.setPrenom(prenominput.getText().toString());
        etd.setEmail(emailinput.getText().toString());
        etd.setLogin(logininput.getText().toString());
        etd.setAdresse(adresseinput.getText().toString());

     etd.setSexe(sexeinput.getSelectedItem().toString());
        etd.setPassword(motdepasseinput.getText().toString());
//       etd.setBytesImage(webC.extractBytes);
        
         cdao.add(etd);
         JOptionPane.showMessageDialog(rootPane, "Bienvenue "+nominput.getText()+" "+prenominput.getText());
         String rec=logininput.getText();
             //String rec2=nominput.getText();    
      //result.setText(result.getText()+""+rec);
        
      HomeClientfatma f=new HomeClientfatma();
  f.loginclient.setText(rec); 
  
   f.show();
    //ImageIcon om = new ImageIcon( webC.getName());
           // System.out.println(webC.getName());
       //f.MyImg.setIcon(om);
        this.hide();
        } 
    }//GEN-LAST:event_sinscrireMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       // webC.initCamera();
        
//        webC.setVisible(true);         
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Ocean".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iNSCRIPTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iNSCRIPTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iNSCRIPTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iNSCRIPTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iNSCRIPTION().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CLOSE;
    private javax.swing.JTextField adresseinput;
    private javax.swing.JLabel bglabel;
    private javax.swing.JLabel drag;
    private javax.swing.JTextField emailinput;
    private javax.swing.JLabel errmsg;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField logininput;
    private javax.swing.JLabel minim;
    private javax.swing.JPasswordField motdepasseinput;
    public javax.swing.JTextField nominput;
    private javax.swing.JLabel notiferrphoto;
    private javax.swing.JTextField prenominput;
    private javax.swing.JComboBox sexeinput;
    private javax.swing.JLabel sinscrire;
    // End of variables declaration//GEN-END:variables

     private void SetIcon() {
      setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
}
