/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.tunisiamall.gui;
import edu.esprit.tunisiamall.gui.LoginGUI;
import edu.esprit.tunisiamall.gui.LoginQRcodeGUI;
import edu.esprit.tunisiamall.technique.DataSource;
import edu.esprit.tunisiamall.entities.Login;
import edu.esprit.tunisiamall.dao.classes.LoginDAO;
import edu.esprit.tunisiamall.entities.Produit;
import edu.esprit.tunisiamall.gui.ResponsableEnseigneGUI;
import org.opencv.core.Core;
import edu.esprit.tunisiamall.technique.DataSource;
import java.awt.Component;
import java.awt.Graphics;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
/**
 *
 * @author Safwene
 */
public class LoginChoiseGUI extends javax.swing.JFrame {

    
    
    
    /**
     * Creates new form LoginGUI
     */
    public LoginChoiseGUI() {
        initComponents();
        this.setTitle("LOGIN");
        this.HelpjLabel.setText("");
        this.setResizable(false);
        this.setLocationRelativeTo(this);
        this.setVisible(true);
      
        this.DessinerBesoinDaide("Pas Encore Inscrit ?",40);
          this.getConnectionDB();
        this.loginusername.setEnabled(true);
                this.qrcode.setEnabled(true);
        
        
   

    }
    
    
      void getConnectionDB(){
          
          
          
        try {
            this.DBconnectionjLabel.setIcon(new ImageIcon("src/edu/esprit/tunisiamall/images/Database-echec-icon.png"));
            this.qrcode.setEnabled(false);
            this.loginusername.setEnabled(false);
            Thread.sleep(1000);
            
            
            if (DataSource.getInstance() != null){
                this.DBconnectionjLabel.setIcon(new ImageIcon("src/edu/esprit/tunisiamall/images/Database-Accept-icon.png"));
                
                
            }
            else {
                this.DBconnectionjLabel.setIcon(new ImageIcon("src/edu/esprit/tunisiamall/images/Database-echec-icon.png"));
                
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(LoginChoiseGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }
      
      
      public void DessinerBesoinDaide(String mot, int sleep){
          
          for (int i=0;i<mot.length();i++){
              try {
                  String word ="";
                  for (int j=0;j<=i;j++){
                      word += mot.charAt(j);
                  }
                  this.HelpjLabel.setText(word);
                  
                  Thread.sleep(sleep);
              } catch (InterruptedException ex) {
                  Logger.getLogger(LoginChoiseGUI.class.getName()).log(Level.SEVERE, null, ex);
              }
              
          }
            
      }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DBconnectionjLabel = new javax.swing.JLabel();
        HelpjLabel = new javax.swing.JLabel();
        qrcode = new javax.swing.JLabel();
        loginusername = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DBconnectionjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/tunisiamall/images/Database-Accept-icon.png"))); // NOI18N
        getContentPane().add(DBconnectionjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 445, -1, -1));

        HelpjLabel.setText("Besoin d'aide ?");
        HelpjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HelpjLabelMouseClicked(evt);
            }
        });
        getContentPane().add(HelpjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        qrcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qrcodeMouseClicked(evt);
            }
        });
        getContentPane().add(qrcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 280, 50));

        loginusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginusernameMouseClicked(evt);
            }
        });
        getContentPane().add(loginusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 280, 50));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/tunisiamall/images/Page1.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 380, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HelpjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpjLabelMouseClicked
  
       this.setVisible(false);
       iNSCRIPTION insc= new iNSCRIPTION();
       insc.setVisible(true);
        
        
    }//GEN-LAST:event_HelpjLabelMouseClicked

    private void qrcodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qrcodeMouseClicked
 this.setVisible(false);
        LoginQRcodeGUI loginQRcodeGUI = new LoginQRcodeGUI();
        loginQRcodeGUI.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_qrcodeMouseClicked

    private void loginusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginusernameMouseClicked
 this.setVisible(false);
        LoginGUI loginGUI = new LoginGUI();
        loginGUI.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_loginusernameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginChoiseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginChoiseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginChoiseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginChoiseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
     //   System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginChoiseGUI();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel DBconnectionjLabel;
    private javax.swing.JLabel HelpjLabel;
    private javax.swing.JLabel loginusername;
    private javax.swing.JLabel qrcode;
    // End of variables declaration//GEN-END:variables
}
