/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.tunisiamall.gui;
import edu.esprit.tunisiamall.technique.DataSource;
import edu.esprit.tunisiamall.entities.Login;
import edu.esprit.tunisiamall.dao.classes.LoginDAO;
import edu.esprit.tunisiamall.entities.Produit;
import edu.esprit.tunisiamall.gui.ResponsableEnseigneGUI;
/**
 *
 * @author Safwene
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
       
        initComponents();
        this.setTitle("LOGIN");
        this.setResizable(false);
        this.setLocationRelativeTo(this);
   
        getConnectionDB();

    }
    
    void getConnectionDB(){
                if (DataSource.getInstance() != null){
                    System.out.println("Connection Etablie !");
                }
                else {
                    System.out.println("Connection Non-etablie !");
                }
                
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsernamejTextField = new javax.swing.JTextField();
        PreviousjLabel = new javax.swing.JLabel();
        passwordjTextField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernamejTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UsernamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 240, 30));
        getContentPane().add(PreviousjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 463, -1, -1));

        passwordjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordjTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 240, 30));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 280, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/tunisiamall/images/sign in.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernamejTextFieldActionPerformed

    private void passwordjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordjTextFieldActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
          // TODO add your handling code here:

        Login login = new Login();
        login.setUsername(this.UsernamejTextField.getText());
        login.setPassword(String.valueOf(this.passwordjTextField.getPassword()));
        LoginDAO loginDAO = new LoginDAO();
       // System.out.println(loginDAO.checkUser(login)[1]);
       
        
        //loginDAO.testMethode();
        
        
        
     
        
        if (loginDAO.checkUser(login)[0].equals("RESPONSABLE")){
            
            this.setVisible(false);
            ResponsableEnseigneGUI responsableEnseigneGUI = ResponsableEnseigneGUI.getInstance();
            responsableEnseigneGUI.setIdResponsableEnseigne(Integer.parseInt(loginDAO.checkUser(login)[1]));
            responsableEnseigneGUI.setInformationsResponsableEnseigne();
            responsableEnseigneGUI.setVisible(true);
            return;

        }
        else if (loginDAO.checkUser(login)[0].equals("ADMIN")){
            this.setVisible(false);
            HomeAdmin homeAdmin = new HomeAdmin();
            homeAdmin.setVisible(true);
            return;
        }
        else if (loginDAO.checkUser(login)[0].equals("CLIENT")){
            this.setVisible(false);
            HomeClientfatma f= new HomeClientfatma();
           f.loginclient.setText(UsernamejTextField.getText()); 
           f.setVisible(true);
            return;
        }
         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PreviousjLabel;
    private javax.swing.JTextField UsernamejTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField passwordjTextField;
    // End of variables declaration//GEN-END:variables
}
