/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.tunisiamall.gui;

import java.awt.Color;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author dali
 */
public class MailSend extends javax.swing.JFrame {

    /**
     * Creates new form MailSend
     */
    private String mailDestinataire = "";
    
    public String getMailDestinataire(){
        return this.mailDestinataire;
    }
    public void setMailDestinataire(String mailDestinataire){
        this.mailDestinataire=mailDestinataire;
    }
    
    
    
    
    
    public MailSend() {
        
        initComponents();
        getContentPane().setBackground(Color.decode("#AAC7CD"));
        this.setLocationRelativeTo(null);
        
        
    }
    
    void setInformationUser(){
         this.Desttxt.setText(mailDestinataire);
         this.Desttxt.setEditable(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Desttxt = new javax.swing.JTextField();
        Sujettxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Mailtext = new javax.swing.JTextArea();
        sendbt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Destinataire ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel2.setText("Sujet");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 61, -1));

        Desttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesttxtActionPerformed(evt);
            }
        });
        getContentPane().add(Desttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 216, -1));
        getContentPane().add(Sujettxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 216, -1));

        Mailtext.setColumns(20);
        Mailtext.setRows(5);
        jScrollPane1.setViewportView(Mailtext);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 185, 384, 220));

        sendbt.setText("Send");
        sendbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendbtActionPerformed(evt);
            }
        });
        getContentPane().add(sendbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 438, -1, -1));

        jLabel3.setText("Mailing");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 69, -1));

        exit.setText("Retour");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 19, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/tunisiamall/images/22.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DesttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DesttxtActionPerformed

    private void sendbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendbtActionPerformed
        // TODO add your handling code here:
        
        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.socketFactory.port", "587");
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.port", "587");
        
        
        Session session= Session.getInstance(props,
             new javax.mail.Authenticator() {
                 protected PasswordAuthentication getPasswordAuthentication(){
                 return new PasswordAuthentication("mohamedali.boughanmi@esprit.tn", "dalio456");
                   
                 } 
             
             }
              
                );
        
       try{
            
           Message message = new MimeMessage (session);
           message.setFrom(new InternetAddress(Desttxt.getText()) );
           message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(Desttxt.getText()));
           message.setSubject("Test Mail");
           message.setText(Mailtext.getText());
           props.put("mail.smtp.starttls.enable", "true");
           Transport.send(message);
           JOptionPane.showMessageDialog(null, "Mail envoyé");
           
       }
       catch(Exception e){
           
           JOptionPane.showMessageDialog(null, e);
       }
       
       
       this.setVisible(false);
        Formulairresp Resp = new Formulairresp();
        Resp.setVisible(true);
        
        
        
        
        
        
        
    }//GEN-LAST:event_sendbtActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Formulairresp resp = new Formulairresp();
        
        
        resp.setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MailSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MailSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MailSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MailSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MailSend().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Desttxt;
    private javax.swing.JTextArea Mailtext;
    private javax.swing.JTextField Sujettxt;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sendbt;
    // End of variables declaration//GEN-END:variables
}
