/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.tunisiamall.gui;

import edu.esprit.tunisiamall.dao.classes.ResponsableEnseigneDAO;
import edu.esprit.tunisiamall.entities.ResponsableEnseigne;
import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dali
 */
public class RespModif extends javax.swing.JFrame {

    /**
     * Creates new form RespModif
     */
    public RespModif() {
        initComponents();
        getContentPane().setBackground(Color.decode("#AAC7CD"));
        this.setLocationRelativeTo(null);
        
        ResponsableEnseigneDAO rdao = new ResponsableEnseigneDAO();
        ResponsableEnseigne resp = new ResponsableEnseigne();
        
        
        List<ResponsableEnseigne> list=rdao.DisplayModif();
        DefaultTableModel model =(DefaultTableModel) TableModif.getModel();
        for(ResponsableEnseigne r:list){
         model.addRow(new Object[]{r.getId(),r.getCin(),r.getNom(),r.getPrenom(),
               r.getLogin(),r.getMail(),r.getAdresse(),r.getTelephone()}); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableModif = new javax.swing.JTable();
        confrim = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableModif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CIN", "NOM ", "PRENOM", "LOGIN", "MAIL", "ADRESSE", "TELEPHONE"
            }
        ));
        jScrollPane1.setViewportView(TableModif);

        confrim.setText("Confirmer");
        confrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confrimActionPerformed(evt);
            }
        });

        exit.setText("Retour");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confrim, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exit, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(exit)
                .addGap(112, 112, 112)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confrim)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confrimActionPerformed
        // TODO add your handling code here:
        
        
      
       // System.out.println(id);
              
        int i=TableModif.getSelectedRow();
        String id=TableModif.getValueAt(i,0).toString();
        String CIN=TableModif.getValueAt(i,1).toString();
        String nom=TableModif.getValueAt(i,2).toString();
        String prenom=TableModif.getValueAt(i,3).toString();
        String login=TableModif.getValueAt(i,4).toString();
        String mail=TableModif.getValueAt(i,5).toString();
        String adresse=TableModif.getValueAt(i,6).toString();
        String telephone=TableModif.getValueAt(i,7).toString();
        
        
        
        DefaultTableModel model =(DefaultTableModel) TableModif.getModel();
        ResponsableEnseigneDAO resp=new ResponsableEnseigneDAO();
      
        resp.update(CIN,nom,prenom,login,mail,adresse,telephone,Integer.parseInt(id));
        
        
        model.removeRow(TableModif.getSelectedRow());
    }//GEN-LAST:event_confrimActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        
        Formulairresp Resp = new Formulairresp();
        Resp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RespModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RespModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RespModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RespModif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RespModif().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableModif;
    private javax.swing.JButton confrim;
    private javax.swing.JButton exit;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
